FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY ["Microservices.Product.Api/Microservices.Product.Api.csproj", "Microservices.Product.Api/"]
RUN dotnet restore "Microservices.Product.Api/Microservices.Product.Api.csproj"

COPY . .
WORKDIR "/src/Microservices.Product.Api"
RUN dotnet build "Microservices.Product.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Microservices.Product.Api.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Microservices.Product.Api.dll"]